### PR TITLE
Use svg instead of png.

### PR DESCRIPTION
**Pull request by marcfehling**
We prepared vector images, but convert them to raster images. We can directly transform tikz standalone images into svg graphics.

This PR replaces png graphics with svg graphics. And we don't need the auxiliary pdf files.

Please verify before merge!

### CODE REVIEW

**Comment by lu-kas** [comment]
Thanks!

This makes sense, however, why do you set the image width to a fixed value and do not use the MD syntax?

**Comment by marcfehling** [comment]
From my experience with markdown, vector graphics will be stretched to the full width of the jupyter-notebook. This might not be optimal for small images or images of large height, so I preferred using the html syntax wherever possible which allows to set a fixed width.

In a same way, we did the same thing before by specifying the image resolution of our raster graphics.

**Comment by lu-kas** [comment]
I was not clear enough. Using svg is definitely the right way to go.

Having a fixed image width in jupyter may seem to make sense, but I would rather prefer something relative. And, in the jupyter-book web-page the fixed width prevents scaling of the images while all other content adopts.

Any ideas for having both, scaling in the book and a size limit in jupyter?

**Comment by marcfehling** [comment]
John Gruber states https://daringfireball.net/projects/markdown/syntax#img
> As of this writing, Markdown has no syntax for specifying the dimensions of an image; if this is important to you, you can simply use regular HTML `` tags.

So we need to use HTML tags. `width` and `height` attributes only accept pixels as values. However it would work if we embed images in a CSS container like
```
<img src="image.svg" style="width:50%" />
```
I have no idea to which width the relative specification belongs. Images will probably change whenever the browser window size changes.

**Comment by lu-kas** [comment]
ok, so I understand your point, although I did not have issues with too large images in jupyter. probably because I do not work with a full width window. making the images 50% of the width does not help either, as it translates directly to the book...

as the main goal is to book, I propose for the time being that we stick to automatic width of the images. once we have discussed the jupyter notebook issue, we can adopt (maybe via css) the image width in the notebooks.

would that be ok for you?

**Comment by marcfehling** [comment]
I am playing around with my browser windows size and try to figure out how `jupyter-book` deals with image scaling. It seems like `jupyter-book` keeps the image width, but once images are embedded in a pipe table, they will be rescaled.

So your suggestion is to use markdown to embed every image?

You may not put multiple images next to each other this way, or let's say that behavior is undefined.

I can prepare a separate PR with all images adjusted to markdown...

**Comment by marcfehling** [comment]
Changes made now all use markdown. We should change the remaining ones to markdown as well, but in a separate PR.

Ready for final review/merge.

**Pull request merged**
